'use client';

import { useState } from 'react';
import type { AcademicEvent } from '@/lib/types';
import { toWareki } from '@/lib/academic';

interface PDFButtonProps {
  events: AcademicEvent[];
  birthYear: number;
  birthMonth: number;
  birthDay: number;
}

export function PDFButton({ events, birthYear, birthMonth, birthDay }: PDFButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    setIsGenerating(true);
    
    try {
      // 動的インポート（クライアントサイドのみ）
      const jsPDFModule = await import('jspdf');
      const jsPDF = jsPDFModule.default;
      
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      // フォント設定（日本語対応のため、シンプルなテキストで出力）
      const pageWidth = doc.internal.pageSize.getWidth();
      let yPos = 20;

      // タイトル
      doc.setFontSize(18);
      doc.text('学歴早見表', pageWidth / 2, yPos, { align: 'center' });
      yPos += 15;

      // 生年月日
      doc.setFontSize(12);
      const birthDateText = `生年月日: ${birthYear}年${birthMonth}月${birthDay}日 (${toWareki(birthYear, birthMonth)})`;
      doc.text(birthDateText, pageWidth / 2, yPos, { align: 'center' });
      yPos += 15;

      // 罫線
      doc.setDrawColor(200);
      doc.line(20, yPos, pageWidth - 20, yPos);
      yPos += 10;

      // 学歴イベント
      doc.setFontSize(10);
      
      events.forEach((event) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        const yearText = `${event.year}年${event.month}月 (${toWareki(event.year, event.month)})`;
        const eventText = event.event;
        const ageText = `${event.age}歳`;

        doc.text(yearText, 25, yPos);
        doc.text(eventText, 80, yPos);
        doc.text(ageText, 170, yPos);
        
        yPos += 8;
      });

      // 罫線
      yPos += 5;
      doc.line(20, yPos, pageWidth - 20, yPos);
      yPos += 10;

      // フッター
      doc.setFontSize(8);
      doc.setTextColor(128);
      doc.text('Generated by 学歴早見表 - sotsugyoutoshihayamihyou.vercel.app', pageWidth / 2, yPos, { align: 'center' });

      // ダウンロード
      doc.save(`学歴早見表_${birthYear}年${birthMonth}月${birthDay}日生まれ.pdf`);
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('PDF生成に失敗しました。ブラウザを更新してもう一度お試しください。');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={isGenerating}
      className="w-full px-4 py-3 rounded-xl font-medium transition-all flex items-center justify-center gap-2"
      style={{
        background: isGenerating ? 'var(--color-border)' : 'var(--color-card)',
        color: isGenerating ? 'var(--color-text-muted)' : 'var(--color-primary)',
        border: '1px solid var(--color-border)',
        cursor: isGenerating ? 'not-allowed' : 'pointer',
      }}
    >
      {isGenerating ? (
        <>
          <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          PDF生成中...
        </>
      ) : (
        <>
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          PDFでダウンロード
        </>
      )}
    </button>
  );
}
